# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."enc-swap" = {
	device = "/dev/disk/by-uuid/b0ee3fcb-d994-440a-9172-28362b586995";
  	keyFile = "/etc/cryptsetup-keys.d/enc-swap.key";
  };

  boot.initrd.secrets = {
  	"/etc/cryptsetup-keys.d/enc-swap.key" = "/etc/cryptsetup-keys.d/enc-swap.key";
  };

  boot.initrd.luks.devices."enc-pv" = {
	device = "/dev/disk/by-uuid/18d8e672-21c7-4061-9e4d-7574829a9c2e";
	allowDiscards = true;
  };

  fileSystems."/" = {
	device = "/dev/mapper/enc-pv";
	fsType = "btrfs";
	options = [ "subvol=root" "compress=zstd" ];
  };


  fileSystems."/home" = {
    device = "/dev/mapper/enc-pv";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd" ];
  };


 fileSystems."/nix" = {
   device = "/dev/mapper/enc-pv";
   fsType = "btrfs";
   options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };


 fileSystems."/persist" = {
   device = "/dev/mapper/enc-pv";
   fsType = "btrfs";
   options = [ "subvol=persist" "compress=zstd" ];
 };


  fileSystems."/var/log" = {
    device = "/dev/mapper/enc-pv";
    fsType = "btrfs";
  	options = [ "subvol=log" "compress=zstd" "noatime" ];
  };


  fileSystems."/boot" ={
    device = "/dev/disk/by-uuid/85E1-DC73";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices =
    [ { device = "/dev/mapper/enc-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
