{ self, inputs, lib, ... }:
let
  inherit (inputs.findFiles) findFiles;

  usersDir = "${self}/users";  # Where users and their data is stored!
  userEntries = builtins.readDir usersDir; # Returns the contents of the users directory and if it's a file or directory
  # Could be combined, but then you can't use usersDir as a single path

  availableUsers =
    builtins.filter # Filters after settings the conditions, and then the list it needs to filter
    (u:
      userEntries.${u} # uses the contents of the usersDir
      == "directory" # Must be a directory
      && builtins.pathExists (usersDir + "/${u}/programs/default.nix")) # A path with a certain file or folder in the usersDir must exist
    (builtins.attrNames userEntries); #List to filter from


 
  # This is basically the template for what folders to search in, and if they exist use findFiles to list each file. These get merged in the users default.nix or equivalent
  getUserDotfiles = username: let # declares the function "getUserDotfiles" and parameter "username"
    dotfilesDir = usersDir + "/${username}/dotfiles"; # sets the users dotfilees directory using the previously declared usersDir plus the structured path with their username as the parameter given by calling function.
  in
    if builtins.pathExists dotfilesDir # checks if the path exists
    then findFiles dotfilesDir # uses findFiles to return every file in the users dotfiles directory
    else {};

in {
  inherit
    availableUsers # allows the list of users previously filterd to be referenced outside this nix
    getUserDotfiles # allows the list of filers previous found to be referenced outside this nix
    ;


in
{
  hjem = {
    # Allows Hjem to safely overwrite pre-existing unmanaged dotfiles
    clobberByDefault = true; 

    users.teajhay = {
      user = "teajhay";
      directory = "/home/teajhay"; # Removed trailing slash (Hjem normalizes home paths)

      # Correctly nesting the dynamic file maps generated by your utility
      xdg.config.files = findFiles "${self}/users/teajhay/xdgConfig";
      # xdg.state.files  = findFiles "${self}/users/teajhay/xdgState";
      # xdg.data.files   = findFiles "${self}/users/teajhay/xdgData";
    files = {
      ".zshrc".source = "${self}/users/teajhay/xdgConfig/.zshrc"
      
    }

    };
  };
}
