{ self, inputs, lib, ... }:
let
inherit (inputs.findFiles) findFiles;
in
{
  hjem = {
    # Allows Hjem to safely overwrite pre-existing unmanaged dotfiles
    clobberByDefault = true; 

    users.teajhay = {
      user = "teajhay";
      directory = "/home/teajhay"; # Removed trailing slash (Hjem normalizes home paths)

      # Correctly nesting the dynamic file maps generated by your utility
      xdg.config.files = findFiles "${self}/users/teajhay/.config";
      # xdg.state.files  = findFiles "${self}/users/teajhay/xdgState";
      # xdg.data.files   = findFiles "${self}/users/teajhay/xdgData";
   # files = {
   #   ".zshrc".source = "${self}/users/teajhay/.zshrc";
   # };

    };
  };
}
