[shorturls]
gh = "github:{path}"
channel = "https://channels.nixos.org/{path}/nixexprs.tar.xz"

[all_follow]
hjem = "hjem"
nixpkgs = ["nixpkgs-stable", "nixpkgs-unstable"]

[omit_inputs]
[signers]
[inputs]

##[inputs.nixpkgs-unstable]
##url = "channel:nixos-unstable"
##
##[inputs.nixpkgs]
##url = "channel:nixos-26.05"

#NOTE: Base inputs
[inputs.nixpkgs]
url = "channel:nixpkgs-unstable"

#NOTE: Maniac preemo soft
[inputs.nixos-core]
url = "github:manic-systems/nixos-core"
group = "rafware"
exclude_follow = ["nixpkgs"]
[inputs.hjem]
url = "github:feel-co/hjem"
group = "rafware"
exclude_follow = ["nixpkgs"]
[inputs.hjem-rum]
url = "github:snugnug/hjem-rum"
group = "rafware"
exclude_follow = ["nixpkgs"]
[inputs.tack]
url = "github:manic-systems/tack"
group = "rafware"

#NOTE: Extra utilities
[inputs.nix-flatpak]
url = "github:gmodena/nix-flatpak"
group = "Extra"
[inputs.nixpkgs-lib]
url = "github:nix-community/nixpkgs.lib"
group = "Extra"
[inputs.nixos-hardware]
url = "github:NixOS/nixos-hardware/master"
group = "Extra"
[inputs.import-tree]
url = "github:denful/import-tree"
group = "Extra"
[inputs.findFiles]
url = "github:Michael-C-Buckley/findFiles.nix"
group = "Extra"
[inputs.niqspkgs]
url = "github:diniamo/niqspkgs"
group = "Extra"
[inputs.hjem-impure]
url = "github:Rexcrazy804/hjem-impure"
group = "Extra"
[inputs.nix-secrets]
url = "github:unnamed-systems/nix-secrets"
group = "Extra"
[inputs.preservation]
url = "github:nix-community/preservation"
group = "Extra"
[inputs.disko]
url = "github:nix-community/disko"
group = "Extra"

#NOTE: Graphical Environment
[inputs.noctalia]
url = "github:noctalia-dev/noctalia/cachix"
group = "Graphical Environment"
exclude_follow = ["nixpkgs"]
[inputs.noctalia-greeter]
url = "github:noctalia-dev/noctalia-greeter"
group = "Graphical Environment"
exclude_follow = ["nixpkgs"]
[inputs.hyprland]
url = "github:hyprwm/Hyprland"
group = "Graphical Environment"
exclude_follow = ["nixpkgs"]

#NOTE: Apps
[inputs.zen-browser]
url = "github:youwen5/zen-browser-flake"
group = "Apps"
[inputs.millennium]
url = "github:SteamClientHomebrew/Millennium"
dir = "packages/nix"
group = "Apps"
