-- Generated by nwg-displays on 2026-08-17 at 08:10:24. Do not edit manually.

--hl.monitor({
--    output = "DP-3",
--    mode = "1920x1080@60.0",
--    position = "0x529",
--    scale = 1.0
--})
--hl.monitor({
--    output = "HDMI-A-1",
--    mode = "3840x2160@120.0",
--    position = "1920x376",
--    scale = 1.2999999999999998,
--    bitdepth = 10
--})


---@module 'hl'

hl.monitor({
  output = "DP-3",
  mode = "1920x1080@60.0",
  position = "0x0",
  scale = 1,
  --disabled = true
})
-- NOTE: Section 'monitorv2' may be a plugin or custom section; verify the output

hl.monitor({
  output = "HDMI-A-1",
  mode = "3840x2160@120.0",
  position = "1920x0",
  scale = 1.5,
  cm = "wide",
  bitdepth = 10,
  vrr = 3,
  --disabled = true,
 -- sdrbrightness = 0.7,
 -- sdrsaturation = 0.3,

})
-- NOTE: Section 'monitorv2' may be a plugin or custom section; verify the output

--monitorv2 {

--    output   = HDMI-A-1

--    disabled = true

--}

hl.config({
    render = {
        cm_auto_hdr = 2,
        direct_scanout = 1,
    },
})
