-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  --

-- Always refer to Hyprland wiki

-- https://wiki.hyprland.org/

-- Initial boot script enable to apply initial wallpapers, theming, new settings etc.

hl.on("hyprland.start", function()
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/initial-boot.sh")
end)

-- suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done

-- as long as the referrence file is present, this initial-boot.sh will not execute

-- Sourcing external config files
-- Pre-configured keybinds, plguins and monitors
Keybinds = require("lua/Configs/Keybinds")
Plugins = require("lua/Configs/Plugins")
Monitors = require("lua/monitors")

-- Load defaults, then user additions/overrides
Startup_Apps = require("lua/Configs/Startup_Apps") -- Startup apps (defaults)
User_apps = require("lua/UserConfigs/Startup_Apps") -- Startup apps (user)

ENVariable = require("lua/Configs/ENVariables") -- Environment variables (defaults)
UserENVariable = require("lua/UserConfigs/ENVariables") -- Environment variables (user)

-- For laptop related. Somewhat working, but potentially change (if I ever want this on a laptop)
--Laptops = require("configs/Laptops")
--UserLaptops = require("UserConfigs/Laptops")
--LaptopDisplay = require("UserConfigs/LaptopDisplay")

-- Load defaults, then user additions
WindowRules = require("lua/Configs/WindowRules") -- Window Rules (defaults)
UserWindowRules = require("lua/UserConfigs/WindowRules") -- Window Rules (user)
LayerRules = require("lua/Configs/LayerRules") -- Layer Rules (defaults)
UserLayerRules = require("lua/UserConfigs/LayerRules") -- Layer Rules (user)
UserWorkspaceRules = require("lua/UserConfigs/WorkspaceRules")


SystemSettings = require("lua/Configs/SystemSettings") -- Default config for hypr 

Decorations = require("lua/UserConfigs/user_decorations") -- Decorations config file
UserAnimations= require("lua/UserConfigs/UserAnimations")-- Animation config file
UserKeybinds= require("lua/UserConfigs/UserKeybinds")-- Put your own keybinds here
UserSettings= require("lua/UserConfigs/UserSettings")-- Main Hyprland Settings.
UserDefaults = require("lua/UserConfigs/01-UserDefaults")-- settings for User defaults apps

