# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #

# This is just created to remove all the themes
#
#

cursor                #990000
cursor_text_color     #000000
background            #000000
foreground            #e8e0e0
selection_foreground  #f5eeee
selection_background  #990000
active_border_color   #990000
inactive_border_color #080707
--url_color             #990000
