-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Commands and Apps to be executed at launch

local LuaScripts = os.getenv("HOME") .. "/.config/hypr/lua/LuaScripts"
-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("sleep 7 && vesktop --ozone-platform-hint=auto --start-minimized")

    --hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("steam -silent")
    hl.exec_cmd("xrandr --output HDMI-A-1 --primary")
    --hl.exec_cmd("/usr/lib/pam_kwallet_init")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
