-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- luacheck: globals hl vim, max_line_length 200
-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- For window rules and layerrules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- This file is used to add or overwrite window rules

-- This file will not be modified during dotfiles updates

hl.window_rule({
  name = "Vesktop-to-special",
  match = { initial_class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$" },
  workspace = "special:Vesktop silent",
  no_initial_focus = true,
})
