-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==================================================

--  KoolDots (2026)

--  Project URL: https://github.com/LinuxBeginnings

--  License: GNU GPLv3

--  SPDX-License-Identifier: GPL-3.0-or-later

-- ==================================================

-- Default settings

-- This is where you put your own settings as this will not be touched during update

-- if the upgrade.sh is used.

-- refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

-- NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf

local scriptsDir = "os.getenv(\"HOME\")/.config/hypr/scripts"

hl.config({
    dwindle = {
        --pseudotile = false    # Not supported 0.55+
        preserve_split = true,
        smart_resizing = true,
        use_active_for_splits = true,
        smart_split = false,
        default_split_ratio = 1.0,
        split_bias = 0,
        precise_mouse_move = false,
        --special_scale_factor = 1,
    },
})

hl.config({
    master = {
        new_status = "slave",
        new_on_top = false,
        new_on_active = "none",
        orientation = "left",
        mfact = 0.55,
        slave_count_for_center_master = 2,
        center_master_fallback = "left",
        smart_resizing = true,
        drop_at_cursor = true,
        always_keep_position = false,
    },
})

hl.config({
    scrolling = {
        -- Default width of new windows (0.1 - 1.0)
        column_width = 0.80,
        -- If only one window is open, should it span the whole screen?
        fullscreen_on_one_column = true,
        -- Direction: right, left, up, or down
        direction = "right",
        -- Center the focused window automatically
        follow_focus = true,
    },
})

hl.config({
    monocle = {
        -- I can't find any settings on the wiki
    },
})
-- NOTE: Section 'monocle' may be a plugin or custom section; verify the output

hl.config({
    general = {
        resize_on_border = true,
        layout = "dwindle",
    },
})

hl.config({
    input = {
        kb_layout = "au",
        repeat_rate = 50,
        repeat_delay = 300,
        sensitivity = 0,
        --mouse sensitivity
        --accel_profile =     # flat or adaptive or blank or EMPTY means libinput’s default mode
        numlock_by_default = true,
        left_handed = false,
        follow_mouse = 1,
        float_switch_override_focus = false,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            clickfinger_behavior = false,
            middle_button_emulation = false,
            tap_to_click = true,
            drag_lock = false,
        },
        -- below for devices with touchdevice ie. touchscreen
        touchdevice = {
            enabled = true,
        },
        -- below is for table see link above for proper variables
        tablet = {
            transform = 0,
            left_handed = 0,
        },
    },
})

--hl.config({
--    gestures = {
--        workspace_swipe_distance = 300,
--        workspace_swipe_touch = false,
--        workspace_swipe_invert = true,
--        workspace_swipe_min_speed_to_force = 30,
--        workspace_swipe_cancel_ratio = 0.5,
--        workspace_swipe_create_new = true,
--        workspace_swipe_direction_lock = true,
--        workspace_swipe_forever = false,
--        workspace_swipe_use_r = false,
--        close_max_timeout = 100,
--        gesture = { 3, "horizontal", "workspace" },
--        gesture = { 3, "up", "dispatcher", "exec", "hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = local_var_2; if (factor < 1) {factor = 1}; print factor * 1.5}')" },
--        gesture = { 3, "down", "dispatcher", "exec", "hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = local_var_2; if (factor < 1) {factor = 1}; print factor / 1.5}')" },
--        gesture = { 4, "up", "dispatcher", "exec", os.getenv("HOME") .. "/.config/hypr/scripts/OverviewToggle.sh" },
--        gesture = { 4, "down", "float" },
--    },
--})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = false,
        -- vfr = true     # Not supported past v0.54.3
        --vrr = 0,
        -- Disabling by default causes MPV to black screen when maximixes 
        --vrr = 0,disabled, 1, alweays on, 2, only on when fullscreen
        mouse_move_enables_dpms = true,
        enable_swallow = false,
        swallow_regex = "^(kitty)$",
        focus_on_activate = true,
        initial_workspace_tracking = 0,
        middle_click_paste = false,
        enable_anr_dialog = true,
        -- Application not Responding (ANR)
        anr_missed_pings = 15,
        -- ANR Threshold default 1 is too low
        allow_session_lock_restore = true,
        -- Prevent lockscreen crash when resume from suspend
        -- This only works with HL v0.53+
        on_focus_under_fullscreen = 1,
        -- 0 - Default, no change
        -- 1 - New focused window takes over fullscreen (Windows-like Alt-Tab)
        -- 2 - New focused window stays behind the fullscreen one
    },
})

--opengl {

--  nvidia_anti_flicker = true

--}

hl.config({
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
})

--Could help when scaling and not pixelating

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
    },
})

hl.config({
    render = {
        direct_scanout = 0,
    },
})

hl.config({
    cursor = {
        sync_gsettings_theme = true,
        no_hardware_cursors = 2,
        -- change to 1 if want to disable
        enable_hyprcursor = true,
        warp_on_change_workspace = 2,
        no_warps = true,
        no_break_fs_vrr = false,
        min_refresh_rate = 24,
        hotspot_padding = 1,
        inactive_timeout = 0,
        zoom_factor = 1.0,
        zoom_rigid = false,
        zoom_detached_camera = true,
        hide_on_key_press = true,
        hide_on_touch = false,
        hide_on_tablet = false,
        use_cpu_buffer = false,
    },
})
