-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==================================================

--  KoolDots (2026)

--  Project URL: https://github.com/LinuxBeginnings

--  License: GNU GPLv3

--  SPDX-License-Identifier: GPL-3.0-or-later

-- ==================================================

-- Vendor defaults for window rules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


--  Some samples on hwo to start apps on specific workspaces

-- windowrule = match:tag email*, workspace 1
hl.workspace_rule({ workspace = "special:mailbox", on_created_empty = "thunderbird"})

hl.window_rule({ name = "email-to-special", match = { initial_class = "org.mozilla.Thunderbird" }, workspace = "special:mailbox silent", no_initial_focus = true, suppress_event = "activate"})

-- windowrule = match:tag browser*, workspace 2

-- windowrule = match:tag projects*, workspace 3

-- windowrule = match:tag screenshare*, workspace 4 silent

-- windowrule = match:tag gamestore*, workspace 5

-- windowrule = match:class ^(virt-manager)$, workspace 6 silent

-- windowrule = match:class ^(.virt-manager-wrapped)$, workspace 6 silent

-- windowrule = match:tag im*, workspace 7

-- windowrule = match:class obsidian, workspace 8

-- windowrule = match:tag games*, workspace 8

-- windowrule = match:tag multimedia*, workspace 9 silent


hl.window_rule({
    no_dim = true,
    idle_inhibit = "fullscreen",
    match = {
        fullscreen = 1,
    },
})

-- TAGS - add apps under appropriate tag to use the same settings

-- browser tags
local browser_rules = {
    { "firefox",  "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$"},
    {"google-chrome",  "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$"},
    {"chrome-default-profile",  "^(chrome-.+-Default)$"},
    {"chromium",  "^([Cc]hromium)$"},
    {"microsoft-edge",  "^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$"},
    {"brave",  "^([Bb]rave-browser(-beta|-dev|-unstable)?)$"},
    {"thorium-cachy",  "^([Tt]horium-browser|[Cc]achy-browser)$"},
    {"zen",  "^(zen-alpha|zen)$"},
}

for _, rule in ipairs(browser_rules) do
    hl.window_rule({
        name = "tag-browser-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+browser",
    })
end

-- notif/shell tag

-- noctalia is not a daemon but shut up

local daemon_rules = {
    { "swaync",  "^(swaync-control-center|swaync-notification-window|swaync-client|class)$"},
    {"noctalia",  "^(dev.noctalia.Noctalia)$"},
    {"mission-center", ""}
}

for _, rule in ipairs(daemon_rules) do
    hl.window_rule({
        name = "tag-daemon-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+daemon",
    })
end

-- KooL settings tag

hl.window_rule({
    name  = "tag-kool-cheat-sheet",
    tag = "+KooL_Cheat",
    match = {
        title = "^(KooL Quick Cheat Sheet)$",
    },
})

hl.window_rule({
    name  = "tag-kool-hyprland-settings",
    tag = "+KooL_Settings",
    match = {
        title = "^(KooL Hyprland Settings)$",
    },
})

hl.window_rule({
    name  = "tag-kool-settings-nwg-tools",
    tag = "+KooL_Settings",
    match = {
        class = "^(nwg-displays|nwg-look)$",
    },
})

-- terminal tags
local term_rules = {
    { "emulators",  "^(ghostty|wezterm|Alacritty|kitty|kitty-dropterm)$"},
}

for _, rule in ipairs(term_rules) do
    hl.window_rule({
        name = "tag-terminal-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+terminal",
    })
end

-- email tags
local mail_rules = {
    { "thunderbird",  "^([Tt]hunderbird|org.mozilla.Thunderbird)$" },
    { "betterbird",    "^(eu.betterbird.Betterbird)$" },
    { "evolution", "^(org.gnome.Evolution)$" },
}

for _, rule in ipairs(mail_rules) do
    hl.window_rule({
        name = "tag-mail-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+email",
    })
end

-- project tags
local project_rules = {
    { "vscodium",  "^(codium|codium-url-handler|VSCodium)$" },
    { "vscode",    "^(VSCode|code|code-url-handler)$" },
    { "zed", "^(dev.zed.Zed|antigravity)$" },
    { "jetbrains",       "^(jetbrains-.+)$" },
}

for _, rule in ipairs(project_rules) do
    hl.window_rule({
        name = "tag-project-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+project",
    })
end

-- screenshare tags
local screenshare_rules = {
    { "obs",  "^(com.obsproject.Studio)$" },
 }

for _, rule in ipairs(screenshare_rules) do
    hl.window_rule({
        name = "tag-screenshare-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+screenshare",
        workspace = "10 silent",
    })
end

-- IM tags

local IM_rules = {
    { "discord-family",  "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$" },
    { "ferdium",    "^([Ff]erdium)$" },
    { "whatsapp", "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$" },
    { "telegram", "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$"},
    { "teams", "^(teams-for-linux)$"},
    { "element", "^(im.riot.Riot|Element)$"},
}

for _, rule in ipairs(IM_rules) do
    hl.window_rule({
        name = "tag-IM-" .. rule[1],
        match = {
            class = rule[2],
        },
        tag = "+im",
    })
end

-- game(store) tags

local game_rules = {
    { "gamescope", { class = "^(gamescope)$" },                           "games" },
    { "steam-app", { class = "^(steam_app_\\d+)$" },                      "games" },
    { "proton",    { xdg_tag = "^(proton-game)$" },                       "games" },
    { "steam",     { class = "^([Ss]team)$" },                        "gamestore" },
    { "lutris",    { title = "^([Ll]utris)$" },                       "gamestore" },
    { "heroic",    { class = "(com.heroicgameslauncher.hgl)$" },      "gamestore" },
}

for _, rule in ipairs(game_rules) do
    hl.window_rule({
        name = "tag-" .. rule[3] .. "-" .. rule[1],
        match = rule[2],
        tag = "+" .. rule[3],
    })
end

-- file-manager tags
local file_manager_rules = {
    { "common", { class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$" }, "file-manager" },
    { "warp",   { class = "^(app.drey.Warp)$" },                              "file-manager" },
}

for _, rule in ipairs(file_manager_rules) do
    hl.window_rule({
        name = "tag-" .. rule[3] .. "-" .. rule[1],
        match = rule[2],
        tag = "+" .. rule[3],
    })
end

-- wallpaper tags

local wallpaper_rules = {
    { "waytrogen", { class = "^([Ww]aytrogen)$" }, "wallpaper" },
    { "waypaper",  { class = "^([Ww]aypaper)$"  }, "wallpaper" },
}

for _, rule in ipairs(wallpaper_rules) do
    hl.window_rule({
        name = "tag-" .. rule[3] .. "-" .. rule[1],
        match = rule[2],
        tag = "+" .. rule[3],
    })
end
-- multimedia tags

local multimedia_rules = {
    { "audacious", { class = "^([Aa]udacious)$" }, "multimedia" },
    { "video-players",  { class = "^([Mm]pv|vlc)$"  }, "multimedia_video" },
}

for _, rule in ipairs(multimedia_rules) do
    hl.window_rule({
        name = "tag-" .. rule[3] .. "-" .. rule[1],
        match = rule[2],
        tag = "+" .. rule[3],
        no_blur = true,
    })
end

-- settings tags

local settings_rules = {
    { "rog-control", { title = "^(ROG Control)$" }, "settings" },
    { "wihotspot",  { class = "^(wihotspot(-gui)?)$"  }, "settings" },
    { "baobab",  { class = "^([Bb]aobab|org.gnome.[Bb]aobab)$"  }, "settings" },
    { "disks-and-hotspot",  { class = "^(gnome-disks|wihotspot(-gui)?)$$"  }, "settings" },
    { "kvantum",  { title = "(Kvantum Manager)"  }, "settings" },
    { "file-roller",  { class = "^(file-roller|org.gnome.FileRoller)$"  }, "settings" },
    { "network-blueman",  { class = "^(nm-applet|nm-connection-editor|blueman-manager)$"  }, "settings" },
    { "pipewire-control",  { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"  }, "settings" },
    { "qtct",  { class = "^(qt5ct|qt6ct)$"  }, "settings" },
    { "xdg-portal-gtk",  { class = "(xdg-desktop-portal-gtk)"  }, "settings" },
    { "polkit-kde",  { class = "^(org.kde.polkit-kde-authentication-agent-1)$"  }, "settings" },
    { "rofi",  { class = "^([Rr]ofi)$"  }, "settings" },
    { "btrfs-assistant",  { class = "^(btrfs-assistant)$"  }, "settings" },
    { "timeshift",  { class = "^(timeshift-gtk)$"  }, "settings" },
}

for _, rule in ipairs(settings_rules) do
    hl.window_rule({
        name = "tag-" .. rule[3] .. "-" .. rule[1],
        match = rule[2],
        tag = "+" .. rule[3],
    })
end

-- viewer tags

local cuck_rules = {
    { "system-monitor", { class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$" }, "hyprglass_enabled" },
    { "system-monitor", { class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$" }, "viewer" },
    { "evince",  { class = "^(evince)$"  }, "viewer" },
    { "image-viewers",  { class = "^(eog|org.gnome.Loupe)$"  }, "viewer" },
}

for _, rule in ipairs(cuck_rules) do
    hl.window_rule({
        name = "tag-" .. rule[3] .. "-" .. rule[1],
        match = rule[2],
        tag = "+" .. rule[3],
    })
end


-- network tags

hl.window_rule({
  name = "tag-network-rule",
  match = { class = "^(nm-connection-editor|nmtui)$"},
  tag = "+network",
})

-- FLOAT

-- layed out as the { "rule name", {match field = "RegEx"}, {optional additonal rules such as centering, size and etc. Enter here as docs say and function will parse it, otherwise discard it if empty}}, All rules here will float

local float_rules = {
    { "zoom-onedriver", { class = "([Zz]oom|onedriver|onedriver-launcher)" }},
    { "video-players", { class = "^(mpv|com.github.rafostar.Clapper)$" }},
    { "qalculate",    { class = "^([Qq]alculate-gtk)$" }, },
    { "center-auth-required-title",     { title = "^(Authentication Required)$" }},
    { "center-polkit-auth-dialog",     { title = "^(Authentication required|Authentication Required)$", class = "^(xfce-polkit|mate-polkit|polkit-mate-authentication-agent-1)$" }, {size = {"monitor_w*0.35", "monitor_h*0.35"}}},
    { "vscodium-secondary-window",     { title = "negative:(.*codium.*|.*VSCodium.*)", class = "(codium|codium-url-handler|VSCodium)" }},
    { "heroic-secondary-window",     { title = "negative:(Heroic Games Launcher)", class = "^(com.heroicgameslauncher.hgl)$" }},
    { "steam-secondary-window",     { title = "negative:^([Ss]team)$", class = "^([Ss]team)$" }},
    { "add-folder-dialog",     { title = "^(Add Folder to Workspace)$"}, {size = {"monitor_w*0.7", "monitor_h*0.6"}}},
    { "save-as-dialog",     { title = "^(Save As)$"}, {size = {"monitor_w*0.7", "monitor_h*0.6"}}},
    { "open-files-dialog",     { initial_title = "(Open Files)"}, {size = {"monitor_w*0.7", "monitor_h*0.6"}}},
    { "sddm-background",     { title = "^(SDDM Background)$"}, {size = {"monitor_w*0.16", "monitor_h*0.12"}}},
    { "yad-dialog",     { class = "^(yad)$"},{size = {"monitor_w*0.2", "monitor_h*0.2"}}},
    { "hyprland-donate",     { class = "^(hyprland-donate-screen)$"}},
    { "pipewire-control",  { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"  }},
    { "network-editor",     { tag = "network"}, {move  = {"monitor_w * 0.99 - window_w", "60"}}},
    { "daemon-tag",     { tag = "daemon"}},
}

for _, rule in ipairs(float_rules) do
    local opts = {
      name = "float-" .. rule[1],
      match = rule[2],
      float = true }
    if rule[3] then
        for k, v in pairs(rule[3]) do
            opts[k] = v
        end
    end
    hl.window_rule(opts)
end

-- complex float rule for stupid fucking extensions thanks to the great ruski


hl.on("window.open", function(w)
    if w.class ~= "firefox" then return end
    if w.initial_title ~= "Mozilla Firefox" then return end

    local ff_windows = hl.get_windows({ class = "firefox" })
    if #ff_windows <= 1 then return end

    hl.dispatch(hl.dsp.window.float({ action = "set", window = w }))

    local sub
    sub = hl.on("window.title", function(tw)
        if tw.address ~= w.address then return end
        if tw.title == ""
            or tw.title == "Mozilla Firefox"
            or tw.title == "about:blank"
            or tw.title:match("^about:.*Mozilla Firefox$") then return end

        sub:remove()

        if tw.title:match("^Extension:") then
            hl.dispatch(hl.dsp.window.resize({ x = 800, y = 600, window = tw }))
            hl.dispatch(hl.dsp.window.center({ window = tw }))
            hl.dispatch(hl.dsp.focus({ window = tw }))
        else
            hl.dispatch(hl.dsp.window.float({ action = "unset", window = tw }))
        end
    end)
end)


-- SIZE

-- POSITION

local position_rules = {
    { "auth-required-title",     { title = "^(Authentication Required)$" }},
    { "polkit-auth-dialog",     { title = "^(Authentication required|Authentication Required)$", class = "^(xfce-polkit|mate-polkit|polkit-mate-authentication-agent-1)$" }},
    { "add-folder-dialog",     { title = "^(Add Folder to Workspace)$"}},
    { "save-as-dialog",     { title = "^(Save As)$"}},
    { "sddm-background",     { title = "^(SDDM Background)$"}, {size = {"monitor_w*0.16", "monitor_h*0.12"}}},
    { "yad-dialog",     { class = "^(yad)$"}},
    { "hyprland-donate",     { class = "^(hyprland-donate-screen)$"}},
    { "rog-control",     { title = "^(ROG Control)$"}},
    { "keybindings",     { title = "^(Keybindings)$"}},
    { "pipewire",     { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"}},
    { "whatsapp",     { class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$"}},
    { "network-editor",     { class = "^(nm-connection-editor)$"}},
    { "nm-auth-dialog",     { class = "^(Wi-Fi Network Authentication Required)$"}},
    { "hyprland-donate",     { class = "^(hyprland-donate-screen)$"}},
    { "hyprland-donate",     { class = "^(hyprland-donate-screen)$"}},
}

for _, rule in ipairs(position_rules) do
    local opts = {
      name = "center-" .. rule[1],
      match = rule[2],
      center = true,
      }
      for k, v in pairs(rule[3] or {}) do
        opts[k] = v
      end
    hl.window_rule(opts)
end

-- OPACITY

local opacity_rules = {
    { "browser",     { tag = "browser" }, "1.0 0.96"},
    { "projects",     { tag = "projects" }, "0.9 0.8" },
    { "multimedia",     { tag = "multimedia"}, "0.94 0.86"},
    { "file-manager",     { tag = "file-manager"}, "0.9 0.8"},
    { "im",     { tag = "im"}, "0.94 0.86"},
    { "terminal",     { tag = "terminal"}, "1 0.8"},
    { "text-editor",     { class = "^(gedit|org.gnome.TextEditor|mousepad)$"}, "0.8 0.7"},
    { "deluge",     { class = "^(deluge)$"}, "0.9 0.8"},
    { "seahorse",     { class = "^(seahorse)$"}, "0.9 0.8"},
    { "text-editor",     { class = "^(gedit|org.gnome.TextEditor|mousepad)$"}, "0.8 0.7"},
}

for _, rule in ipairs(opacity_rules) do
    local opts = {
      name = "opacity-" .. rule[1] .. "-tag",
      match = rule[2],
      opacity = rule[3],
      }
      for k, v in pairs(rule[4] or {}) do
        opts[k] = v
      end
    hl.window_rule(opts)
end



-- BLUR & FULLSCREEN

-- This is not gonna take the focus to the window that appears

-- when hovering over some of the parts of the IntelliJ Products

-- name: no-initial-focus-jetbrains

hl.window_rule({
    name  = "match_class___jetbra",
    match = {
        class = "no_initial_focus on",
    },
    -- TODO: review rule: "match:class ^(jetbrains-.*)$"
})

-- name: no-initial-focus-wind-title

hl.window_rule({
    name  = "match_title___wind__",
    match = {
        class = "no_initial_focus on",
    },
    -- TODO: review rule: "match:title ^(wind.*)$"
})

-- workspaces

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-3",
    default = true,
})

hl.workspace_rule({
   workspace = "2",
   monitor = "HDMI-A-1",
   default = true,
})
--
----workspace = 3
--
----workspace = 4
--
----workspace = 5
--
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
})

--workspace = 8

--workspace = 9

--workspace = 10

hl.window_rule({
    name  = "Picture-in-Picture",
    match = {
        title = "^[Pp]icture-in-[Pp]icture$",
    },
    float = true,
    move = { "72%", "7%" },
    opacity = "0.95 0.75",
    pin = true,
    keep_aspect_ratio = true,
    size = { "(monitor_w*0.3)", "(monitor_h*0.3)" },
})

-- Named rule for CachyOS Kernel Manager

hl.window_rule({
    name  = "CachyOS Kernel Manager",
    match = {
        class = "^(org.cachyos.KernelManager)$",
        title = "^(CachyOS Kernel Manager)$",
        initial_class = "^(org.cachyos.KernelManager)$",
        initial_title = "^(CachyOS Kernel Manager)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for Mainline Kernels

hl.window_rule({
    name  = "Mainline Kernels",
    match = {
        class = "^(mainline-gtk)$",
        title = "^(Mainline Kernels)$",
        initial_class = "^(mainline-gtk)$",
        initial_title = "^(Mainline Kernels)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.45)", "(monitor_h*0.55)" },
})

-- Named rule for Kwallet

hl.window_rule({
    name  = "Kwallet",
    match = {
        class = "^(org.kde.kwalletmanager)$",
        title = "^(Wallet Manager)$",
        initial_class = "^(org.kde.kwalletmanager)$",
        initial_title = "^(Wallet Manager)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for NVIDIA Settings

hl.window_rule({
    name  = "NVIDIA Settings",
    match = {
        class = "^(nvidia-settings)$",
        title = "^(NVIDIA Settings)$",
        initial_class = "^(nvidia-settings)$",
        initial_title = "^(NVIDIA Settings)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for CachyOS Package Installer

hl.window_rule({
    name  = "CachyOS Package Installer",
    match = {
        class = "^(org.cachyos.cachyos-pi)$",
        title = "^(CachyOS Package Installer)$",
        initial_class = "^(org.cachyos.cachyos-pi)$",
        initial_title = "^(CachyOS Package Installer)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for Shelly

hl.window_rule({
    name  = "Shelly",
    match = {
        class = "^(com.shellyorg.shelly)$",
        title = "^(Shelly)$",
        initial_class = "^(com.shellyorg.shelly)$",
        initial_title = "^(Shelly)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for CachyOS Hello

hl.window_rule({
    name  = "CachyOS Hello",
    match = {
        class = "^(CachyOSHello)$",
        title = "^(CachyOS Hello)$",
        initial_class = "^(CachyOSHello)$",
        initial_title = "^(CachyOS Hello)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for Cache Cleaner - Octopi

hl.window_rule({
    name  = "Cache Cleaner- Octopi",
    match = {
        class = "^(octopi-cachecleaner)$",
        title = "^(Cache Cleaner- Octopi)$",
        initial_class = "^(octopi-cachecleaner)$",
        initial_title = "^(Cache Cleaner- Octopi)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for Octopi Package Manager

hl.window_rule({
    name  = "Octopi Package Manager",
    match = {
        class = "^(octopi)$",
        title = "^(Octopi)$",
        initial_class = "^(octopi)$",
        initial_title = "^(Octopi)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for Repository Editor - Octopi

hl.window_rule({
    name  = "Repository Editor- Octopi",
    match = {
        class = "^(octopi-repoeditor)$",
        title = "^(Repository Editor- Octopi)$",
        initial_class = "^(octopi-repoeditor)$",
        initial_title = "^(Repository Editor- Octop)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for KooL Cheat (tag)

hl.window_rule({
    name  = "KooL Cheat (tag)",
    match = {
        tag = "KooL_Cheat",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.65)", "(monitor_h*0.9)" },
})

-- Named rule for Wallpaper (tag)

hl.window_rule({
    name  = "Wallpaper (tag)",
    match = {
        tag = "wallpaper",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
    opacity = "0.9 0.7",
})

-- Named rule for Settings (tag)

hl.window_rule({
    name  = "Settings (tag)",
    match = {
        tag = "settings",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
    opacity = "0.8 0.7",
})

-- Named rule for Viewer (tag)

hl.window_rule({
    name  = "Viewer (tag)",
    match = {
        tag = "viewer",
    },
    float = true,
    center = true,
    opacity = "0.82 0.75",
})

-- Named rule for KooL Settings (tag)

hl.window_rule({
    name  = "KooL Settings (tag)",
    match = {
        tag = "KooL-Settings",
    },
    float = true,
    center = true,
})

-- Named rule for Multimedia Video (tag)

hl.window_rule({
    name  = "Multimedia Video (tag)",
    match = {
        tag = "multimedia_video",
    },
    no_blur = true,
    opacity = 1.0,
})

-- Named rule for Games (tag)

hl.window_rule({
    name  = "Games (tag)",
    match = {
        tag = "games",
    },
    no_blur = true,
    fullscreen = 0,
})

-- Named rule for Ferdium

hl.window_rule({
    name  = "Ferdium",
    match = {
        class = "^([Ff]erdium)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

-- Named rule for Gnome Calculator

hl.window_rule({
    name  = "Gnome Calculator",
    match = {
        class = "(org.gnome.Calculator)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.55)", "(monitor_h*0.45)" },
})

-- Named rule for qa

hl.window_rule({
    name  = "qalculate-gtk",
    match = {
        class = "(qalculate-gtk)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.25)", "(monitor_h*0.50)" },
})

-- Named rule for Thunar Dialogs

hl.window_rule({
    name  = "Thunar Dialogs",
    match = {
        class = "([Tt]hunar)",
        title = "negative:(.*[Tt]hunar.*)",
    },
    float = true,
    center = false,
})

-- Named rule for Bitwarden

hl.window_rule({
    name  = "Bitwarden",
    match = {
        class = "^(Bitwarden)$",
        title = "^(Bitwarden)$",
        initial_class = "^(Bitwarden)$",
        initial_title = "^(Bitwarden)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for hyprpwcenter audio control panel

hl.window_rule({
    name  = "hyprland audio panel",
    match = {
        class = "^(hyprpwcenter)$",
        title = "^(Pipewire Control Center)$",
        initial_class = "^(hyprpwcenter)$",
        initial_title = "^(Pipewire Control Center)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for Garuda Assistant

hl.window_rule({
    name  = "Garuda Assistant",
    match = {
        class = "^(garuda-assistant)$",
        title = "^(Garuda Assistant)$",
        initial_class = "^(garuda-assistant)$",
        initial_title = "^(Garuda Assistant)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Named rule for HyprMod HL config GUI

hl.window_rule({
    name  = "HyprMod GUI",
    match = {
        class = "^(com.github.hyprmod)$",
        title = "^(HyprMod)$",
        initial_class = "^(com.github.hyprmod)$",
        initial_title = "^(HyprMod)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.75)" },
})

-- Named rule for EasyEffects

hl.window_rule({
    name  = "EasyEffects",
    match = {
        class = "^(com.github.wwmm.easyeffects)$",
        title = "^(Easy Effects)$",
        initial_class = "^(com.github.wwmm.easyeffects)$",
        initial_title = "^(Easy Effects)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.65)" },
})

-- Named rule for Megasync

hl.window_rule({
    name  = "Megasync",
    match = {
        class = "^(nz\\.co\\.mega\\.megasync)$",
        initial_class = "^(nz\\.co\\.mega\\.megasync)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.1)", "(monitor_h*0.3)" },
})

-- Named rule for Mousam weather GUI

hl.window_rule({
    name  = "Mousam Weather",
    match = {
        class = "^(io.github.amit9838.mousam)$",
        title = "^(Mousam)$",
        initial_class = "^(io.github.amit9838.mousam)$",
        initial_title = "^(Mousam)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.75)" },
})
