# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D4D1D0
background         #1D0D0C
cursor             #2D0C0F

active_tab_foreground     #1D0D0C
active_tab_background     #D4D1D0
inactive_tab_foreground   #D4D1D0
inactive_tab_background   #1D0D0C

active_border_color   #D4D1D0
inactive_border_color #1D0D0C
bell_border_color     #6A111B

color0      #A19D9C
color1		#6A111B
color2		#4F0F16
color3		#190B0C
color4		#140B0B
color5		#140B0A
color6		#170908
color7		#400A10
color8		#631019
color9		#8E1724
color10		#6A141D
color11		#220F0F
color12		#1A0F0E
color13		#1B0E0E
color14		#1E0B0A
color15		#BE8389
