-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==================================================

--  KoolDots (2026)

--  Project URL: https://github.com/LinuxBeginnings

--  License: GNU GPLv3

--  SPDX-License-Identifier: GPL-3.0-or-later

-- ==================================================

-- Commands and Apps to be executed at launch (vendor defaults)

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

local UserScripts = os.getenv("HOME") .. "/.config/hypr/UserScripts"

local lock = os.getenv("HOME") .. "/.config/hypr/scripts/LockScreen.sh"

local SwwwRandom = os.getenv("HOME") .. "/.config/hypr/UserScripts/WallpaperAutoChange.sh"

local livewallpaper = ""

local wallDIR = os.getenv("HOME") .. "/Pictures/wallpapers"

-- change path manually here if needed

--## wallpaper stuff ###


--exec-once = sh -c 'sleep 2; $HOME/.config/hypr/scripts/WallpaperDaemon.sh'

--exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

-- wallpaper random

--exec-once = $SwwwRandom $wallDIR # random wallpaper switcher every 30 minutes

--## Startup ###






-- For ubuntu


--exec-once = ags

--exec-once = blueman-applet

--exec-once = rog-control-center




-- Quickshell Overview




-- NOTE: Dropterminal is currently certified only with kitty. Not all terminals behave correctly as a dropdown.


-- Clipboard manager



-- Rainbow borders (disabled by default; use quick settings menu)


-- Here are list of features available but disabled by default

-- Persistent wallpaper

-- exec-once = sh -c '$HOME/.config/hypr/scripts/WallpaperDaemon.sh && (command -v awww >/dev/null 2>&1 && awww img "$wallDIR/mecha-nostalgia.png" || swww img "$wallDIR/mecha-nostalgia.png")'

-- Gnome polkit for NixOS

--exec-once = $scriptsDir/Polkit-NixOS.sh

-- xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)

--exec-once = $scriptsDir/PortalHyprland.sh




-- Quickshell Overview

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia")
    hl.exec_cmd("hypr-cursor-warp")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd(scriptsDir .. "/Polkit.sh")
    hl.exec_cmd("nm-applet")
    -- hl.exec_cmd("nm-tray")
    --hl.exec_cmd("swaync")
    hl.exec_cmd(scriptsDir .. "/PortalHyprland.sh")
    --hl.exec_cmd(scriptsDir .. "/WaybarStartup.sh")
    --hl.exec_cmd("qs -c overview")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(scriptsDir .. "/LuaAutoReload.sh")
    hl.exec_cmd(scriptsDir .. "/Hyprsunset.sh init")
    --hl.exec_cmd(scriptsDir .. "/Dropterminal.sh --startup kitty")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(UserScripts .. "/RainbowBorders.sh")
    hl.exec_cmd("blueman-applet --no-tray")
    hl.exec_cmd(scriptsDir .. "/KeybindsLayoutInit.sh")
    hl.exec_cmd("qs -c overview")
end)
