color0 #26292c
color1 #fd4663
color2 #67c3e4
color3 #6580e0
color4 #8f75dc
color5 #93d4ec
color6 #96a7e9
color7 #f2f3f3
color8 #626a6e
color9 #fd4663
color10 #67c3e4
color11 #6580e0
color12 #8f75dc
color13 #93d4ec
color14 #96a7e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #000000
background            #000000
foreground            #f2f3f3
selection_foreground  #afb4b6
selection_background  #26292c
active_border_color   #67c3e4
inactive_border_color #0e1114
url_color             #67c3e4

active_tab_foreground   #182125
active_tab_background   #67c3e4
inactive_tab_foreground #afb4b6
inactive_tab_background #0e1114
cursor_trail_color      #afb4b6
