name: update tacks
"on":
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-tacks:
    name: update tacks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=flake:nixpkgs
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: tack update
        run: nix run github:manic-systems/tack -- update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update tacks"
          title: "chore: update tacks"
          branch: automation/update-tacks
          delete-branch: true
