-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==================================================

--  KoolDots (2026)

--  Project URL: https://github.com/LinuxBeginnings

--  License: GNU GPLv3

--  SPDX-License-Identifier: GPL-3.0-or-later

-- ==================================================

-- For layerrules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- This file is used to add or overwrite layer rules

-- This file will not be modified during dotfiles updates

-- Example:

-- layerrule = blur on, ignore_alpha 0, match:namespace rofi
